name: Feature/Enhancement Request
description: Request a new feature or enhancement
title: "[FEATURE REQUEST]: "
labels: ["Type: Enhancement", "Triage Required"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! OpenHornet lives on its community contributions and reports!
  - type: input
    id: contact
    attributes:
      label: Discord Username
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Noctum#4085
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Feature/Enhancement Summary
      description: Please summarize your issue here. Be as specific as possible.
      placeholder: Tell us what you want see!
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes: 
      label: Actual Results
      description: What actually happened?
      placeholder: Be very specific. The more detail, the better we can analyze the issue. Copy/Paste error messages directly and completely. Context matters!
    validations:
      required: true
  - type: textarea
    id: images
    attributes: 
      label: Screenshots/Images/Files
      description: Pictures/Files are worth 1000 words. Take some pictures or a video of the unexpected behavior, show us where you think the bad code is, put together a quick power point description of the issue, drop in a .INO file of a fix you made - you can't put too much information here!
      placeholder: You can just paste images, videos or files in this field...
    validations:
      required: false
  - type: input
    id: part-numbers
    attributes:
      label: Applicable File Names
      description: List the file(s) this issue applies to.
      placeholder: ex. 1A1A1-RS485_BUS_MASTER_UIP.ino, 1A2-MASTER_ARM_PANEL.ino, etc.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Release Version
      description: What release are you working with?
      options:
        - v0.3.0
        - v0.2.0
        - pre-v0.2.0 (Early Development/Alpha)
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Is this a mechanical and/or electrical issue or artwork? Mechanical being physical parts like structure, seat, mechanisms, etc. Electrical would be PCBs, wiring, etc. Artwork would be placards, stickers, dataplates or a vector art issue. (You may select more than one.) 
      multiple: true
      options:
        - embedded (Arduino Sketches/Microcontroller embedded software)
        - Libraries & Dependencies (Arduino Libraries, etc)
        - DCS-BIOS
        - Documentation
    validations:
        required: true
  - type: dropdown
    id: end-item
    attributes:
      label: Applicable End Item(s)
      description: What End Item(s) does this issue apply to? 
      multiple: true
      options:
        - Top Level Assembly (TLA)
        - Upper Instrument Panel (UIP)
        - Lower Instrument Panel (LIP)
        - Center Tub (CT)
        - Left Console (LCON)
        - Right Console (RCON)
        - Flight Stick
        - Throttle
    validations:
        required: true
  - type: checkboxes
    id: built-to-print
    attributes:
      label: Hardware is built to print & this software is tested on that hardware?
      description: Did you build this part to the relevant drawing, using parts specified by OpenHornet? (It's okay if you didn't, just describe how you deviated in the Miscellaneous Info text area below.)
      options:
        - label: I built (or attempted to build) the part to the OpenHornet print without any deviations and tested the software on it.
        - label: I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)
          required: true
  - type: textarea
    id: misc
    attributes: 
      label: Miscellaneous Info
      description: Do you have any additional information not previously covered?
      placeholder: This space would be to provide specific code snippets and versions, list deviations from the OpenHornet build, or provide any information that is not covered elsewhere in this report.
    validations:
      required: false